apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy-task3

spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-task3
  
  template:
    metadata:
      name: deploy-task3
      labels:
        app: deploy-task3
  
    spec:
      volumes:
      - name: storage-task3
        persistentVolumeClaim:
          claimName: pvc-task3
      containers:
      - name: deploy-task3
        image: akansh028/apache-webserver-php
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: "/var/www/html"
            name: storage-task3
      
